const allProjects = {
    project0: {
        id:"",
        nombre: "",
        name: "",
        contenido: "",
        content: "",
        link: "",
        githubLink: "",
        imagen: "",
    },
    project1: {
        id:"Project1",
        nombre: "DriveIn",
        name: "DriveIn",
        contenido: "Una concesionaria localizada en las ciudades turisticas mas visitadas de latinoamerica donde tu puedes rentar el vehiculo que mas te guste de nuetro catalogo. Este sitio web fue creado como grupo en un periodo de 4 semanas, con sprints cada semana.",
        content: "A concessionary located in the most visited tourist cities in Latin America where you can rent the vehicle you like from our catalog. This website was created as a group in a period of 4 weeks, with a sprint each week.",
        link: "https://drivein.vercel.app/",
        githubLink: "https://github.com/Naotari/DriveIn",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1674577847/Portfolio/Projects/DriveIn.png",
    },
    project2: {
        id:"Project2",
        nombre: "Razas de Perros",
        name: "Dog Breeds",
        contenido: "Un catalogo de razas de perros donde puedes encontrar todas las razas existentes, ademas puedes añadir tu perro a la coleccion. Esta fue mi primera pagina web creada.",
        content: "A catalog of dog breeds where you can find all breeds existence, also you can add your dog to the collection. This was my first web created.",
        link: "https://dog-breeds-naotari.vercel.app/",
        githubLink: "https://github.com/Naotari/Dog-Breeds",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1674578526/Portfolio/Projects/DogBreeds.png",
    },
    project3: {
        id:"Project3",
        nombre: "Mi portafolio",
        name: "My Portfolio",
        contenido: "Esta es la pagina que diseñe para mostrar toda la informacion acerca de mi y los proyectos que he hecho.",
        content: "This is the web I desiged to show all information about me and the projects I made.",
        link: "https://portfolio-naotari.vercel.app/",
        githubLink: "https://github.com/Naotari/Portfolio",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1674591580/Portfolio/Projects/Portfolio.png",
    },
    project4: {
        id:"Project4",
        nombre: "Calculadora",
        name: "Calculator",
        contenido: "Esta es una calculadora basica creada para practicar conceptos basicos de javascript.",
        content: "This is a basic calculator created to practice basic concepts in javascript.",
        link: "https://calculator-naotari.vercel.app/",
        githubLink: "https://github.com/Naotari/calculator",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1695327335/Portfolio/Projects/Calculator.png",
    },
}
export default allProjects